[target.aarch64-linux-android]
linker = "C:/soft/Android/sdk/ndk/26.2.11394342/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android30-clang.cmd"

[target.armv7-linux-androideabi]
linker = "C:/soft/Android/sdk/ndk/26.2.11394342/toolchains/llvm/prebuilt/windows-x86_64/bin/armv7a-linux-androideabi30-clang.cmd"
