[target.aarch64-linux-android]
linker = "C:/soft/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android34-clang.cmd"

[target.armv7-linux-androideabi]
linker = "C:/soft/Android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/bin/armv7a-linux-androideabi34-clang.cmd"
